services:
  # API service
  api:
    build:
      context: deploy/
      dockerfile: API.Dockerfile
    ports:
      - "5001:80"
    volumes:
      - type: bind
        source: ./htdocs/
        target: /var/www/html/
    container_name: rs_api
    networks:
      - rs_network
    healthcheck:
      test: ["CMD", "apache2ctl", "-M"]
      start_period: 30s
      interval: 15s
      timeout: 5s
      retries: 3

networks:
  rs_network:
    external: true
    name: rs_network
